-- CreateTable
CREATE TABLE `AccountBook` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `isPrivate` BOOLEAN NOT NULL DEFAULT true,
    `name` VARCHAR(255) NOT NULL,
    `aliasName` VARCHAR(255) NOT NULL,
    `createdAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updatedAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
