version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/drcloud-deploy
permissions:
  - object: /home/ubuntu/drcloud-deploy
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu