

version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: dev-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: rlaehdwns99@
      POSTGRES_DB: uliga_dev
    ports:
      - "15432:5432"
    volumes:
      - postgres_data_uliga_dev:/var/lib/postgresql/data
    networks:
      - dev

  redis:
    image: redis:7
    container_name: dev-redis
    restart: unless-stopped
    ports:
      - "16379:6379"
    networks:
      - dev

networks:
  dev:

volumes:
  postgres_data_uliga_dev: